{
 "title": "Front-end Errors",
 "description": "Front-end Errors",
 "tags": [
  "gep",
  "rum",
  "errors"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Faro error events",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "{app_name=\"gep-scm-web\"} |= \"ErrorEvent\""
    }
   ]
  },
  {
   "title": "Console error logs",
   "type": "logs",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "{app_name=\"gep-scm-web\"} |= \"\\\"level\\\":\\\"error\\\"\""
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(faro_errors_total[1m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}